---
# defaults file for roles/app_servers

flask_app_name: resource_hub
flask_user: flask
flask_home: /opt/
flask_repo: https://github.com/tonykay/resource_hub.git
flask_scm_ref: main
flask_app_lauch_script: /usr/local/bin/launch_resource_hub
virtualenv_name: "venv-{{ flask_app_name }}"
virtualenv_home: /opt/virtual_envs
virtualenv_python: /usr/bin/python3

app_yum_repo:
  - "http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/perl-Thread-Queue-3.13-1.el8.noarch.rpm"
  - "http://repo.okay.com.mx/centos/8/x86_64/release/autoconf-2.69-27.el8.noarch.rpm"
  - "http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/m4-1.4.18-7.el8.x86_64.rpm"
  - "http://repo.okay.com.mx/centos/8/x86_64/release/automake-1.16.1-6.el8.noarch.rpm"
  - "http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/libtool-2.4.6-25.el8.x86_64.rpm"

app_yum_packages:
  - autoconf
  - automake
  - git
  - gcc
  - libtool
  - python3
  - python3-psycopg2

pip_dependencies:
  - virtualenv
  - psycopg2-binary==2.8.6
